### ISSUE TITLE
Listing style lltx typo

### ISSUE THREAD

**Issue by Ionizing** [Liam0205/easy_slides#1]
In `listings`' document, there is no programming language named `LaTeX`, but `TeX` ONLY.
 https://github.com/Liam0205/easy_slides/blob/224dba2f2f5e8cdb9a13b70353da9858988ba0e6/global_setup/settings.tex#L51

What the document said:
<img width="418" alt="image" src="https://user-images.githubusercontent.com/17506747/50321503-20d3ab00-050c-11e9-8dad-02aaf1c0f2bc.png">
I think it's a typo.

**Comment by Ionizing** [comment]
Compiler would give errors if using like this:
```
\begin{lstlisting}[style=lltx]
balabala..
\end{lstlisting}
```

**Comment by Liam0205** [comment]
@IonizingRadiation lmc...

**Comment by Liam0205** [comment]
@IonizingRadiation It's a typo of easy_slides, not listings.

For LaTeX, it's treated as a dialect of TeX in the listings package. Hence, to specify LaTeX as a language in listings environment, one should write codes as language = {[LaTeX]TeX}. 

This will be fixed soon.

**Comment by Ionizing** [comment]
Thanks for your quick response and fixing.
