### ISSUE TITLE
Background image position not proper when being compiled for first time

### ISSUE THREAD

**Issue by Ionizing** [Liam0205/easy_slides#2]
Just as the title says, the background image isn't in the correct position if I compile only once. The layout would be well if I compile again.

<img width="730" alt="image" src="https://user-images.githubusercontent.com/17506747/55400291-03d55c00-5580-11e9-9587-8a0a31e42bdd.png">

Although I can get the correct output by compiling again, but it feels somewhat ... uncomfortable.

OS: macOS 10.13
XeTeX, Version 3.14159265-2.6-0.99999 (TeX Live 2018)
`easy_slides` version v1.2 (latest version).

**Comment by Ionizing** [comment]
You can reproduce it by compiling the demo inside the `easy_slides` template.

**Comment by Liam0205** [comment]
That's a known issue, and I think it's a feature of TeX.

The position background figure is decided by `.aux` file, which requires at least two-pass compile.
